# Generated by Django 5.2.3 on 2025-09-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="imports/newsletter/")),
                (
                    "error_report",
                    models.FileField(
                        blank=True, null=True, upload_to="imports/newsletter/errors/"
                    ),
                ),
                ("list_id", models.IntegerField(blank=True, null=True)),
                ("list_slug", models.CharField(blank=True, max_length=120)),
                ("create_list", models.BooleanField(default=False)),
                ("confirm_all", models.BooleanField(default=False)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_created", models.IntegerField(default=0)),
                ("rows_updated", models.IntegerField(default=0)),
                ("rows_skipped", models.IntegerField(default=0)),
                ("rows_errors", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("data", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ingest.importjob",
                    ),
                ),
            ],
        ),
    ]
