# Generated by Django 5.2.3 on 2025-09-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importjob",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="importjob",
            name="dry_run",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="confirm_all",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="error_report",
            field=models.FileField(blank=True, null=True, upload_to="imports/errors/"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(upload_to="imports/"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="list_slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("validating", "validating"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="ImportRow",
        ),
    ]
