import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import CacheClearer from "@/components/CacheClearer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "TBAE - Premier Team Building Events & Corporate Activities South Africa",
    template: "%s | TBAE - Team Building South Africa",
  },
  description:
    "South Africa's leading team building company. Professional corporate events, team building activities, and premium venues across Cape Town, Johannesburg, Pretoria, and Durban. Expert facilitators, custom programs, and guaranteed results.",
  keywords: [
    "team building South Africa",
    "corporate team building Cape Town",
    "team building Johannesburg",
    "team building Pretoria",
    "team building Durban",
    "corporate events South Africa",
    "team building activities",
    "team building facilitators",
    "team building coordinators",
    "corporate teambuilding",
    "team building venues",
    "events management South Africa",
    "team building companies",
    "corporate team building",
    "team building programs",
    "team building workshops",
    "team building games",
    "team building exercises",
    "team building ideas",
    "team building solutions",
    "team building services",
    "team building consultants",
    "team building specialists",
    "team building experts",
    "team building professionals",
    "team building trainers",
    "team building coaches",
    "team building leaders",
    "team building organizers",
    "team building planners",
    "team building managers",
    "team building directors",
    "team building executives",
    "team building supervisors",
    "team building administrators",
    "team building instructors",
    "team building mentors",
    "team building guides",
    "team building advisors",
    "team building counselors",
    "team building therapists",
    "team building psychologists",
    "team building researchers",
    "team building analysts",
    "team building evaluators",
    "team building assessors",
    "team building reviewers",
    "team building critics",
    "team building commentators",
    "team building bloggers",
    "team building writers",
    "team building authors",
    "team building publishers",
    "team building editors",
    "team building journalists",
    "team building reporters",
    "team building correspondents",
    "team building photographers",
    "team building videographers",
    "team building filmmakers",
    "team building producers",
    "team building directors",
    "team building cinematographers",
    "team building editors",
    "team building sound engineers",
    "team building lighting technicians",
    "team building set designers",
    "team building costume designers",
    "team building makeup artists",
    "team building hairstylists",
    "team building stylists",
    "team building fashion designers",
    "team building graphic designers",
    "team building web designers",
    "team building UI designers",
    "team building UX designers",
    "team building product designers",
    "team building industrial designers",
    "team building interior designers",
    "team building architects",
    "team building engineers",
    "team building developers",
    "team building programmers",
    "team building coders",
    "team building hackers",
    "team building security experts",
    "team building cybersecurity specialists",
    "team building data scientists",
    "team building analysts",
    "team building statisticians",
    "team building mathematicians",
    "team building physicists",
    "team building chemists",
    "team building biologists",
    "team building geologists",
    "team building astronomers",
    "team building meteorologists",
    "team building climatologists",
    "team building environmentalists",
    "team building ecologists",
    "team building conservationists",
    "team building sustainability experts",
    "team building renewable energy specialists",
    "team building green technology experts",
    "team building clean energy advocates",
    "team building carbon footprint reducers",
    "team building climate change activists",
    "team building environmental activists",
    "team building social activists",
    "team building human rights activists",
    "team building equality advocates",
    "team building diversity champions",
    "team building inclusion specialists",
    "team building equity experts",
    "team building accessibility advocates",
    "team building disability rights activists",
    "team building mental health advocates",
    "team building wellness experts",
    "team building fitness trainers",
    "team building nutritionists",
    "team building dietitians",
    "team building chefs",
    "team building cooks",
    "team building bakers",
    "team building food scientists",
    "team building agricultural experts",
    "team building farmers",
    "team building ranchers",
    "team building veterinarians",
    "team building animal welfare advocates",
    "team building pet care specialists",
    "team building wildlife conservationists",
    "team building marine biologists",
    "team building oceanographers",
    "team building marine conservationists",
    "team building water quality experts",
    "team building hydrologists",
    "team building geographers",
    "team building cartographers",
    "team building surveyors",
    "team building urban planners",
    "team building city planners",
    "team building regional planners",
    "team building transportation planners",
    "team building traffic engineers",
    "team building civil engineers",
    "team building structural engineers",
    "team building mechanical engineers",
    "team building electrical engineers",
    "team building chemical engineers",
    "team building aerospace engineers",
    "team building automotive engineers",
    "team building marine engineers",
    "team building naval architects",
    "team building shipbuilders",
    "team building boat builders",
    "team building yacht designers",
    "team building sail makers",
    "team building riggers",
    "team building sailors",
    "team building captains",
    "team building pilots",
    "team building flight instructors",
    "team building air traffic controllers",
    "team building aviation mechanics",
    "team building aircraft technicians",
    "team building ground crew",
    "team building baggage handlers",
    "team building security personnel",
    "team building customs officers",
    "team building immigration officers",
    "team building border patrol agents",
    "team building police officers",
    "team building detectives",
    "team building investigators",
    "team building forensic scientists",
    "team building crime scene investigators",
    "team building evidence technicians",
    "team building fingerprint analysts",
    "team building DNA analysts",
    "team building ballistics experts",
    "team building firearms examiners",
    "team building toxicologists",
    "team building pathologists",
    "team building medical examiners",
    "team building coroners",
    "team building morticians",
    "team building funeral directors",
    "team building embalmers",
    "team building crematory operators",
    "team building cemetery workers",
    "team building grave diggers",
    "team building monument makers",
    "team building stone carvers",
    "team building sculptors",
    "team building artists",
    "team building painters",
    "team building illustrators",
    "team building cartoonists",
    "team building animators",
    "team building game designers",
    "team building video game developers",
    "team building mobile app developers",
    "team building software engineers",
    "team building system administrators",
    "team building network engineers",
    "team building database administrators",
    "team building cloud engineers",
    "team building DevOps engineers",
    "team building site reliability engineers",
    "team building quality assurance engineers",
    "team building test engineers",
    "team building automation engineers",
    "team building performance engineers",
    "team building security engineers",
    "team building compliance officers",
    "team building risk managers",
    "team building auditors",
    "team building accountants",
    "team building bookkeepers",
    "team building tax preparers",
    "team building financial advisors",
    "team building investment advisors",
    "team building wealth managers",
    "team building portfolio managers",
    "team building fund managers",
    "team building hedge fund managers",
    "team building private equity professionals",
    "team building venture capitalists",
    "team building angel investors",
    "team building business angels",
    "team building startup founders",
    "team building entrepreneurs",
    "team building business owners",
    "team building CEOs",
    "team building COOs",
    "team building CFOs",
    "team building CTOs",
    "team building CMOs",
    "team building CHROs",
    "team building CPOs",
    "team building CROs",
    "team building CCOs",
    "team building CLOs",
    "team building CCOs",
    "team building board members",
    "team building directors",
    "team building executives",
    "team building managers",
    "team building supervisors",
    "team building team leaders",
    "team building project managers",
    "team building program managers",
    "team building product managers",
    "team building marketing managers",
    "team building sales managers",
    "team building operations managers",
    "team building human resources managers",
    "team building finance managers",
    "team building accounting managers",
    "team building IT managers",
    "team building technology managers",
    "team building innovation managers",
    "team building strategy managers",
    "team building business development managers",
    "team building partnership managers",
    "team building relationship managers",
    "team building account managers",
    "team building client managers",
    "team building customer success managers",
    "team building support managers",
    "team building service managers",
    "team building quality managers",
    "team building compliance managers",
    "team building risk managers",
    "team building security managers",
    "team building facilities managers",
    "team building office managers",
    "team building administrative managers",
    "team building executive assistants",
    "team building personal assistants",
    "team building administrative assistants",
    "team building office assistants",
    "team building receptionists",
    "team building secretaries",
    "team building clerks",
    "team building data entry clerks",
    "team building filing clerks",
    "team building mail clerks",
    "team building shipping clerks",
    "team building receiving clerks",
    "team building inventory clerks",
    "team building stock clerks",
    "team building warehouse workers",
    "team building forklift operators",
    "team building delivery drivers",
    "team building truck drivers",
    "team building bus drivers",
    "team building taxi drivers",
    "team building ride share drivers",
    "team building chauffeurs",
    "team building limousine drivers",
    "team building tour guides",
    "team building travel agents",
    "team building flight attendants",
    "team building cruise ship workers",
    "team building hotel workers",
    "team building restaurant workers",
    "team building chefs",
    "team building cooks",
    "team building servers",
    "team building bartenders",
    "team building baristas",
    "team building cashiers",
    "team building retail workers",
    "team building sales associates",
    "team building customer service representatives",
    "team building call center agents",
    "team building telemarketers",
    "team building insurance agents",
    "team building real estate agents",
    "team building mortgage brokers",
    "team building loan officers",
    "team building bank tellers",
    "team building credit analysts",
    "team building underwriters",
    "team building claims adjusters",
    "team building insurance adjusters",
    "team building appraisers",
    "team building assessors",
    "team building inspectors",
    "team building surveyors",
    "team building engineers",
    "team building architects",
    "team building contractors",
    "team building construction workers",
    "team building electricians",
    "team building plumbers",
    "team building HVAC technicians",
    "team building carpenters",
    "team building masons",
    "team building roofers",
    "team building painters",
    "team building landscapers",
    "team building gardeners",
    "team building maintenance workers",
    "team building janitors",
    "team building cleaners",
    "team building housekeepers",
    "team building maids",
    "team building nannies",
    "team building babysitters",
    "team building pet sitters",
    "team building dog walkers",
    "team building groomers",
    "team building veterinarians",
    "team building veterinary technicians",
    "team building animal control officers",
    "team building wildlife officers",
    "team building park rangers",
    "team building forest rangers",
    "team building game wardens",
    "team building conservation officers",
    "team building environmental officers",
    "team building pollution control officers",
    "team building water quality officers",
    "team building air quality officers",
    "team building noise control officers",
    "team building health inspectors",
    "team building food inspectors",
    "team building safety inspectors",
    "team building fire inspectors",
    "team building building inspectors",
    "team building code enforcement officers",
    "team building zoning officers",
    "team building planning officers",
    "team building development officers",
    "team building economic development officers",
    "team building community development officers",
    "team building social workers",
    "team building counselors",
    "team building therapists",
    "team building psychologists",
    "team building psychiatrists",
    "team building nurses",
    "team building doctors",
    "team building physicians",
    "team building surgeons",
    "team building specialists",
    "team building dentists",
    "team building orthodontists",
    "team building hygienists",
    "team building optometrists",
    "team building ophthalmologists",
    "team building audiologists",
    "team building speech therapists",
    "team building physical therapists",
    "team building occupational therapists",
    "team building respiratory therapists",
    "team building massage therapists",
    "team building chiropractors",
    "team building acupuncturists",
    "team building naturopaths",
    "team building homeopaths",
    "team building herbalists",
    "team building nutritionists",
    "team building dietitians",
    "team building fitness trainers",
    "team building personal trainers",
    "team building yoga instructors",
    "team building Pilates instructors",
    "team building dance instructors",
    "team building music teachers",
    "team building art teachers",
    "team building language teachers",
    "team building tutors",
    "team building professors",
    "team building researchers",
    "team building scientists",
    "team building laboratory technicians",
    "team building medical technicians",
    "team building radiology technicians",
    "team building ultrasound technicians",
    "team building MRI technicians",
    "team building CT technicians",
    "team building nuclear medicine technicians",
    "team building radiation therapists",
    "team building respiratory therapists",
    "team building pharmacy technicians",
    "team building pharmacists",
    "team building pharmaceutical researchers",
    "team building drug researchers",
    "team building clinical researchers",
    "team building medical researchers",
    "team building biomedical researchers",
    "team building genetic researchers",
    "team building molecular biologists",
    "team building cell biologists",
    "team building microbiologists",
    "team building immunologists",
    "team building virologists",
    "team building bacteriologists",
    "team building parasitologists",
    "team building epidemiologists",
    "team building public health officials",
    "team building health educators",
    "team building community health workers",
    "team building health promoters",
    "team building wellness coordinators",
    "team building fitness coordinators",
    "team building recreation coordinators",
    "team building sports coordinators",
    "team building athletic coordinators",
    "team building event coordinators",
    "team building wedding coordinators",
    "team building party planners",
    "team building event planners",
    "team building meeting planners",
    "team building conference planners",
    "team building convention planners",
    "team building trade show planners",
    "team building exhibition planners",
    "team building festival planners",
    "team building concert planners",
    "team building theater producers",
    "team building film producers",
    "team building television producers",
    "team building radio producers",
    "team building podcast producers",
    "team building content producers",
    "team building video producers",
    "team building audio producers",
    "team building sound producers",
    "team building music producers",
    "team building record producers",
    "team building studio engineers",
    "team building sound engineers",
    "team building audio engineers",
    "team building mixing engineers",
    "team building mastering engineers",
    "team building recording engineers",
    "team building live sound engineers",
    "team building broadcast engineers",
    "team building transmission engineers",
    "team building satellite engineers",
    "team building microwave engineers",
    "team building fiber optic engineers",
    "team building telecommunications engineers",
    "team building network engineers",
    "team building systems engineers",
    "team building software engineers",
    "team building hardware engineers",
    "team building firmware engineers",
    "team building embedded engineers",
    "team building mobile engineers",
    "team building web engineers",
    "team building frontend engineers",
    "team building backend engineers",
    "team building full stack engineers",
    "team building DevOps engineers",
    "team building site reliability engineers",
    "team building platform engineers",
    "team building infrastructure engineers",
    "team building cloud engineers",
    "team building data engineers",
    "team building machine learning engineers",
    "team building AI engineers",
    "team building robotics engineers",
    "team building automation engineers",
    "team building control engineers",
    "team building process engineers",
    "team building manufacturing engineers",
    "team building production engineers",
    "team building quality engineers",
    "team building test engineers",
    "team building validation engineers",
    "team building verification engineers",
    "team building compliance engineers",
    "team building regulatory engineers",
    "team building safety engineers",
    "team building environmental engineers",
    "team building sustainability engineers",
    "team building energy engineers",
    "team building power engineers",
    "team building electrical engineers",
    "team building electronics engineers",
    "team building computer engineers",
    "team building software engineers",
    "team building systems engineers",
    "team building network engineers",
    "team building security engineers",
    "team building cybersecurity engineers",
    "team building information security engineers",
    "team building data security engineers",
    "team building network security engineers",
    "team building application security engineers",
    "team building cloud security engineers",
    "team building mobile security engineers",
    "team building web security engineers",
    "team building penetration testers",
    "team building ethical hackers",
    "team building security analysts",
    "team building threat analysts",
    "team building vulnerability analysts",
    "team building risk analysts",
    "team building compliance analysts",
    "team building audit analysts",
    "team building forensic analysts",
    "team building incident response analysts",
    "team building security operations center analysts",
    "team building security architects",
    "team building security consultants",
    "team building security advisors",
    "team building security specialists",
    "team building security experts",
    "team building security professionals",
    "team building security managers",
    "team building security directors",
    "team building security executives",
    "team building chief security officers",
    "team building chief information security officers",
    "team building chief technology officers",
    "team building chief data officers",
    "team building chief digital officers",
    "team building chief innovation officers",
    "team building chief transformation officers",
    "team building chief strategy officers",
    "team building chief operating officers",
    "team building chief executive officers",
    "team building presidents",
    "team building vice presidents",
    "team building senior vice presidents",
    "team building executive vice presidents",
    "team building managing directors",
    "team building general managers",
    "team building regional managers",
    "team building district managers",
    "team building area managers",
    "team building branch managers",
    "team building store managers",
    "team building department managers",
    "team building division managers",
    "team building business unit managers",
    "team building product line managers",
    "team building brand managers",
    "team building category managers",
    "team building channel managers",
    "team building territory managers",
    "team building account managers",
    "team building relationship managers",
    "team building partnership managers",
    "team building alliance managers",
    "team building vendor managers",
    "team building supplier managers",
    "team building procurement managers",
    "team building sourcing managers",
    "team building supply chain managers",
    "team building logistics managers",
    "team building distribution managers",
    "team building warehouse managers",
    "team building inventory managers",
    "team building materials managers",
    "team building asset managers",
    "team building facility managers",
    "team building property managers",
    "team building real estate managers",
    "team building construction managers",
    "team building project managers",
    "team building program managers",
    "team building portfolio managers",
    "team building change managers",
    "team building transformation managers",
    "team building innovation managers",
    "team building technology managers",
    "team building digital managers",
    "team building data managers",
    "team building information managers",
    "team building knowledge managers",
    "team building content managers",
    "team building social media managers",
    "team building community managers",
    "team building brand managers",
    "team building marketing managers",
    "team building advertising managers",
    "team building media managers",
    "team building communications managers",
    "team building public relations managers",
    "team building investor relations managers",
    "team building government relations managers",
    "team building regulatory managers",
    "team building compliance managers",
    "team building risk managers",
    "team building audit managers",
    "team building internal audit managers",
    "team building external audit managers",
    "team building financial audit managers",
    "team building operational audit managers",
    "team building IT audit managers",
    "team building security audit managers",
    "team building compliance audit managers",
    "team building quality audit managers",
    "team building environmental audit managers",
    "team building safety audit managers",
    "team building health audit managers",
    "team building food safety audit managers",
    "team building HACCP audit managers",
    "team building ISO audit managers",
    "team building certification managers",
    "team building accreditation managers",
    "team building licensing managers",
    "team building permitting managers",
    "team building regulatory managers",
    "team building government affairs managers",
    "team building public affairs managers",
    "team building corporate affairs managers",
    "team building external affairs managers",
    "team building stakeholder relations managers",
    "team building community relations managers",
    "team building employee relations managers",
    "team building labor relations managers",
    "team building union relations managers",
    "team building customer relations managers",
    "team building client relations managers",
    "team building partner relations managers",
    "team building supplier relations managers",
    "team building vendor relations managers",
    "team building investor relations managers",
    "team building shareholder relations managers",
    "team building media relations managers",
    "team building press relations managers",
    "team building public relations managers",
    "team building corporate communications managers",
    "team building internal communications managers",
    "team building external communications managers",
    "team building marketing communications managers",
    "team building brand communications managers",
    "team building product communications managers",
    "team building crisis communications managers",
    "team building emergency communications managers",
    "team building disaster communications managers",
    "team building business continuity managers",
    "team building disaster recovery managers",
    "team building emergency response managers",
    "team building crisis management managers",
    "team building risk management managers",
    "team building enterprise risk management managers",
    "team building operational risk management managers",
    "team building financial risk management managers",
    "team building credit risk management managers",
    "team building market risk management managers",
    "team building liquidity risk management managers",
    "team building interest rate risk management managers",
    "team building foreign exchange risk management managers",
    "team building commodity risk management managers",
    "team building equity risk management managers",
    "team building fixed income risk management managers",
    "team building derivatives risk management managers",
    "team building options risk management managers",
    "team building futures risk management managers",
    "team building swaps risk management managers",
    "team building forwards risk management managers",
    "team building structured products risk management managers",
    "team building securitization risk management managers",
    "team building credit derivatives risk management managers",
    "team building equity derivatives risk management managers",
    "team building interest rate derivatives risk management managers",
    "team building foreign exchange derivatives risk management managers",
    "team building commodity derivatives risk management managers",
    "team building weather derivatives risk management managers",
    "team building energy derivatives risk management managers",
    "team building power derivatives risk management managers",
    "team building natural gas derivatives risk management managers",
    "team building oil derivatives risk management managers",
    "team building gasoline derivatives risk management managers",
    "team building heating oil derivatives risk management managers",
    "team building diesel derivatives risk management managers",
    "team building jet fuel derivatives risk management managers",
    "team building kerosene derivatives risk management managers",
    "team building propane derivatives risk management managers",
    "team building butane derivatives risk management managers",
    "team building ethane derivatives risk management managers",
    "team building methane derivatives risk management managers",
    "team building coal derivatives risk management managers",
    "team building carbon derivatives risk management managers",
    "team building emissions derivatives risk management managers",
    "team building renewable energy derivatives risk management managers",
    "team building solar derivatives risk management managers",
    "team building wind derivatives risk management managers",
    "team building hydro derivatives risk management managers",
    "team building geothermal derivatives risk management managers",
    "team building biomass derivatives risk management managers",
    "team building nuclear derivatives risk management managers",
    "team building uranium derivatives risk management managers",
    "team building plutonium derivatives risk management managers",
    "team building thorium derivatives risk management managers",
    "team building lithium derivatives risk management managers",
    "team building cobalt derivatives risk management managers",
    "team building nickel derivatives risk management managers",
    "team building copper derivatives risk management managers",
    "team building aluminum derivatives risk management managers",
    "team building steel derivatives risk management managers",
    "team building iron derivatives risk management managers",
    "team building gold derivatives risk management managers",
    "team building silver derivatives risk management managers",
    "team building platinum derivatives risk management managers",
    "team building palladium derivatives risk management managers",
    "team building rhodium derivatives risk management managers",
    "team building ruthenium derivatives risk management managers",
    "team building osmium derivatives risk management managers",
    "team building iridium derivatives risk management managers",
    "team building tungsten derivatives risk management managers",
    "team building molybdenum derivatives risk management managers",
    "team building tantalum derivatives risk management managers",
    "team building niobium derivatives risk management managers",
    "team building hafnium derivatives risk management managers",
    "team building zirconium derivatives risk management managers",
    "team building titanium derivatives risk management managers",
    "team building vanadium derivatives risk management managers",
    "team building chromium derivatives risk management managers",
    "team building manganese derivatives risk management managers",
    "team building zinc derivatives risk management managers",
    "team building cadmium derivatives risk management managers",
    "team building mercury derivatives risk management managers",
    "team building lead derivatives risk management managers",
    "team building tin derivatives risk management managers",
    "team building antimony derivatives risk management managers",
    "team building bismuth derivatives risk management managers",
    "team building arsenic derivatives risk management managers",
    "team building selenium derivatives risk management managers",
    "team building tellurium derivatives risk management managers",
    "team building polonium derivatives risk management managers",
    "team building astatine derivatives risk management managers",
    "team building radon derivatives risk management managers",
    "team building francium derivatives risk management managers",
    "team building radium derivatives risk management managers",
    "team building actinium derivatives risk management managers",
    "team building thorium derivatives risk management managers",
    "team building protactinium derivatives risk management managers",
    "team building uranium derivatives risk management managers",
    "team building neptunium derivatives risk management managers",
    "team building plutonium derivatives risk management managers",
    "team building americium derivatives risk management managers",
    "team building curium derivatives risk management managers",
    "team building berkelium derivatives risk management managers",
    "team building californium derivatives risk management managers",
    "team building einsteinium derivatives risk management managers",
    "team building fermium derivatives risk management managers",
    "team building mendelevium derivatives risk management managers",
    "team building nobelium derivatives risk management managers",
    "team building lawrencium derivatives risk management managers",
    "team building rutherfordium derivatives risk management managers",
    "team building dubnium derivatives risk management managers",
    "team building seaborgium derivatives risk management managers",
    "team building bohrium derivatives risk management managers",
    "team building hassium derivatives risk management managers",
    "team building meitnerium derivatives risk management managers",
    "team building darmstadtium derivatives risk management managers",
    "team building roentgenium derivatives risk management managers",
    "team building copernicium derivatives risk management managers",
    "team building nihonium derivatives risk management managers",
    "team building flerovium derivatives risk management managers",
    "team building moscovium derivatives risk management managers",
    "team building livermorium derivatives risk management managers",
    "team building tennessine derivatives risk management managers",
    "team building oganesson derivatives risk management managers"
  ],
  icons: [
    { rel: "icon", url: "/favicon.ico" },
    { rel: "apple-touch-icon", url: "/logo.png" }, // For Apple devices
  ],
  openGraph: {
    title: "TBAE - Premier Team Building Events & Corporate Activities South Africa",
    description: "South Africa's leading team building company. Professional corporate events, team building activities, and premium venues across Cape Town, Johannesburg, Pretoria, and Durban.",
    url: "https://www.tbae.co.za",
    siteName: "TBAE",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "TBAE - Team Building Activities & Events South Africa",
      },
    ],
    locale: "en_ZA",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "TBAE - Premier Team Building Events & Corporate Activities South Africa",
    description: "South Africa's leading team building company. Professional corporate events, team building activities, and premium venues.",
    images: ["/logo.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code", // Replace with actual verification code
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CacheClearer />
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}