# Generated by Django 5.2.3 on 2025-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('event_type', models.CharField(choices=[('Team Building', 'Team Building'), ('Corporate Event', 'Corporate Event'), ('Workshop', 'Workshop'), ('Virtual Event', 'Virtual Event'), ('Other', 'Other')], max_length=32)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('spam', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
