# Generated by Django 5.2.3 on 2025-09-22 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subscriber",
            options={"ordering": ["email"]},
        ),
        migrations.AddField(
            model_name="delivery",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
