# Generated by Django 5.2.3 on 2025-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_list_options_alter_subscriber_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="client_date_added",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="contact_date_added",
            field=models.DateField(blank=True, null=True),
        ),
    ]
