# Generated by Django 5.2.3 on 2025-10-11 01:09

import django.db.models.deletion
import newsletter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subscriber_client_date_added_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('validating', 'validating'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_errors', models.IntegerField(default=0)),
                ('error_report', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='newsletter.list'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='newsletter.template'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletter.campaign'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletter.subscriber'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='token',
            field=models.CharField(default=newsletter.models.gen_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='confirm_token',
            field=models.CharField(default=newsletter.models.gen_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='tags',
            field=models.JSONField(blank=True, default=newsletter.models.subscriber_tags_default),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(default=newsletter.models.gen_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['campaign', 'sent_at'], name='newsletter__campaig_66b7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['token'], name='newsletter__token_c0c6e5_idx'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importjob',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='newsletter.list'),
        ),
    ]
