# Generated by Django 5.2.3 on 2025-06-20 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=100)),
                ('alt', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(max_length=100)),
                ('bannerImage', models.ImageField(upload_to='homepage/')),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='testimonials/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
