# Generated by Django 5.2.3 on 2025-06-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq_faqcategory_delete_event_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Pages'},
        ),
        migrations.AddField(
            model_name='about',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='about',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest Link'),
        ),
        migrations.AddField(
            model_name='about',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='about',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='about',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp Link'),
        ),
        migrations.AddField(
            model_name='about',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
